# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Flashcards' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flashcards
  pod 'AFNetworking', '~> 3.0'
  pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', branch: '3_0_0'
  pod 'Material', '~> 1.0'

end
