# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Flashcards' do
  platform :ios, '8.3'
  use_frameworks!

  # Pods for Flashcards
  pod 'Parse'

  target 'FlashcardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlashcardsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end