# Uncomment this line to define a global platform for your project
platform :ios, '8.3'

target 'Flashcards' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flashcards
  pod 'AFNetworking', '~> 3.0'
  pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', branch: '3_0_0'
  pod 'DrawerController', '~> 1.1'
  pod 'Koloda', '~> 3.1.2'
  pod 'IQKeyboardManagerSwift'
  pod 'HanekeSwift'
  #pod 'Toast-Swift', '~> 2.0.0'
  pod 'JLToast', '~> 1.4'
 
end

post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end